#!/usr/bin/env ruby
#emma = . -- -- .-

char2morse = {
  a: "*-",
  b: "-***",
  c: "-*-*",
  d: "-**",
  e: "*",
  f: "**-*",
  g: "--*",
  h: "****",
  i: "**",
  j: "*---",
  k: "-*-",
  l: "*-**",
  m: "--",
  n: "-*",
  o: "---",
  p: "*--*",
  q: "--*-",
  r: "*-*",
  s: "***",
  t: "-",
  u: "**-",
  v: "***-",
  w: "*--",
  x: "-**-",
  y: "-*--",
  z: "--**",
}

input = STDIN.read

input.each_char do |c|
  print char2morse[c.to_sym] || c
  print " "
end
